name: "Test wordpress-version-checker"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2.2.0
        with:
          name: lib
          path: lib

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - run: npm ci
      - run: npm run lint
